### PR TITLE
Add QEMU_NO_VNC to start-qemu for disabling VNC

### PR DESCRIPTION
**Pull request by MaxPeal**

### CODE REVIEW

**Comment by MaxPeal** [comment]
a run of update.sh is still needed

**Comment by tianon** [comment]
I'm +1 on the `start-qemu` change, but I'm not a fan of the `README.md` changes -- the usage of `/home/jsmith` was intentional to make sure it wasn't something someone could copy/paste directly since it's intended to be an example folks adapt to their own use case. :sweat_smile:

Can you split those out?  (If you'd rather, I'm happy to update your PR for you. :+1:)

**Comment by MaxPeal** [comment]
shure you can update my PR and remove the changes form the README.md

**Comment by tianon** [comment]
Thank you! :+1:

**Pull request merged**
