### PR TITLE
--disable-numa, fixit runing it inside a cloud vm

### PR DESCRIPTION
**Pull request by MaxPeal**
testet on hetzner cloud

### CODE REVIEW

**Comment by tianon** [comment]
The NUMA functionality is useful though, right?  See https://github.com/tianon/docker-qemu/issues/6 -- if the `SYS_NICE` capability is added to the containers, they do work (and are able to use NUMA properly).

**Comment by MaxPeal** [comment]
in CI systems its often not possibil to set SYS_NICE,

is it possibil to disable the NUMA functionality on runtime?

**Comment by tianon** [comment]
Did some research and found that Debian is applying a patch for this very case: https://salsa.debian.org/qemu-team/qemu/-/blob/1ea32ebc60b18d6d61994ed8be6c76c90a2d9a52/debian/patches/hostmem-dont-use-mbind-if-host-nodes-is-empty.patch

It appears that it's under discussion upstream at https://www.mail-archive.com/qemu-devel@nongnu.org/msg699348.html, but I can't find any record of it actually being applied to the upstream Git tree yet. :disappointed:

**Comment by tianon** [comment]
Aha, found the canonical source!
(https://github.com/qemu/qemu/blob/ddc760832fa8cf5e93b9d9e6e854a5114ac63510/MAINTAINERS#L2196)

It's under the `machine-next` branch in https://github.com/ehabkost/qemu:

https://github.com/ehabkost/qemu/commit/08ec0d4e2bf3e73229ce7a4e537a57794848d319

I'll look to get this patch added to our builds ASAP. :+1:

**Comment by tianon** [comment]
Ok, closing this in favor of https://github.com/tianon/docker-qemu/issues/6, and I'll have a PR open shortly! :+1:

(Thanks for the additional prod to look into this again!)

**Comment by MaxPeal** [comment]
thanks for Backporting the patch

**Pull request closed without merging**
